name: Build schema
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm i
      - run: npx sanity-codegen schema-codegen
      - uses: actions/upload-artifact@v2
        with:
          name: schema-types.d.ts
          path: schema-types.d.ts
